project:
  type: book

book:
  title: "Efficient Machine Learning with R"
  subtitle: "Low-Compute Predictive Modeling with tidymodels"
  author: "Simon P. Couch"
#  date: "3/21/2024"
  chapters:
    - index.qmd
    - 01-intro.qmd
#    - 02-models.qmd
    - 03-parallelism.qmd
#    - 04-search.qmd
    - 05-submodel.qmd
    - references.qmd
    
bibliography: references.bib

format:
  html:
    theme: [cosmo]
    mainfont: 'Montserrat'
    fig-width: 6
    fig-height: 4.25
    fig-align: center
    tbl-cap-location: bottom
    fig-cap-location: bottom
    message: false
    warning: false
    
  pdf:
    documentclass: scrreprt

editor: visual

