project:
  type: book

book:
  title: "Efficient Machine Learning with R"
  subtitle: "Low-Compute Predictive Modeling with tidymodels"
  author: "Simon"
  date: "3/21/2024"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-models.qmd
    - 03-preprocessing.qmd
    - 04-tuning.qmd
    - references.qmd

execute: 
  cache: true

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

